#!/bin/bash
# Cascade CLI wrapper script

CLI_DIR="/Users/dalenavi/Library/Developer/Xcode/DerivedData/cascade-ledger-cutusmwflwtsdbaewikxjysqhrjj/Build/Products/Debug"
exec "$CLI_DIR/cascade-ledger-cli" "$@"
